#!/bin/bash

# ============================================
# Git 自动提交脚本 (macOS版本)
# 由macOS定时服务控制执行时间
# 每40分钟执行一次，仅在工作日9:00-20:30之间运行
# ============================================

# 日志函数
log_message() {
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo "[$timestamp] $1"
}

# 配置区域 - 请根据实际情况修改
GIT_REPO_PATH="/Users/harrisking/code/AI-Movies-Fe" # 修改为您的Git仓库路径
REMOTE_BRANCH="feat/llc/liteCreate" # 远程分支名称

# 5个目标文件数组
TS_FILES=(
    "src/utils/tracking.ts"
    "src/models/logger.ts"
    "src/constants/helpers.ts"
    "src/utils/constants.ts"
    "src/utils/validation.ts"
)

# 20个中文提交信息
CHINESE_COMMITS=(
    "feat: 类型定义错误"
    "feat: 接口参数类型不正确"
    "feat: 函数返回值类型定义"
    "feat: 变量类型声明问题"
    "feat: 泛型参数类型"
    "feat: 类型推断错误"
    "feat: 类型导入问题"
    "feat: 模块导出类型"
    "feat: 类型注解错误"
    "feat: 类型兼容性问题"
    "feat: 联合类型定义"
    "feat: 交叉类型错误"
    "feat: 类型别名定义"
    "feat: 枚举类型声明"
    "feat: 类型保护函数"
    "feat: 类型映射问题"
    "feat: 条件类型错误"
    "feat: 工具类型定义"
    "feat: 类型声明文件"
    "feat: 类型检查配置"
)

# 20个中文功能描述
CHINESE_DESCRIPTIONS=(
    "修复用户登录接口类型"
    "修复订单处理函数返回类型"
    "修复数据验证工具类型定义"
    "修复API请求参数类型声明"
    "修复错误处理函数类型"
    "修复表单验证类型检查"
    "修复日期处理工具类型"
    "修复权限检查函数类型"
    "修复数据转换函数返回类型"
    "修复缓存管理工具类型"
    "修复文件上传接口类型"
    "修复分页查询参数类型"
    "修复搜索过滤器类型定义"
    "修复排序函数比较类型"
    "修复加密解密函数类型"
    "修复数据格式化工具类型"
    "修复国际化函数参数类型"
    "修复主题配置接口类型"
    "修复性能监控工具类型"
    "修复日志记录函数类型"
)

# 20个中文详细描述
CHINESE_DETAILS=(
    "修复了类型定义中的错误，提高了类型安全性"
    "修正了接口参数类型，避免了潜在的类型错误"
    "更新了函数返回类型定义，确保类型一致性"
    "修复了变量类型声明，提高了代码可维护性"
    "优化了泛型参数类型定义，增强了类型推断"
    "修正了类型推断错误，改进了开发体验"
    "修复了类型导入问题，确保了模块正确性"
    "更新了模块导出类型，提高了代码质量"
    "修正了类型注解错误，增强了代码可读性"
    "修复了类型兼容性问题，避免了运行时错误"
    "优化了联合类型定义，提高了类型灵活性"
    "修正了交叉类型错误，改进了类型组合"
    "更新了类型别名定义，简化了复杂类型"
    "修复了枚举类型声明，增强了类型约束"
    "修正了类型保护函数，提高了类型安全性"
    "优化了类型映射，改进了代码可维护性"
    "修复了条件类型错误，增强了类型推断"
    "更新了工具类型定义，提高了开发效率"
    "修正了类型声明文件，确保了类型正确性"
    "修复了类型检查配置，改进了开发体验"
)

# 进入仓库目录
cd "$GIT_REPO_PATH" || {
    log_message "错误: 无法进入仓库目录: $GIT_REPO_PATH"
    exit 1
}

# 随机选择一个目标文件
TS_FILE_PATH=${TS_FILES[$RANDOM % ${#TS_FILES[@]}]}

log_message "开始执行Git自动提交脚本"
log_message "仓库路径: $(pwd)"
log_message "目标文件: $TS_FILE_PATH"

# 检查Git仓库状态
check_git_status() {
    if [ ! -d .git ]; then
        log_message "错误: 当前目录不是Git仓库"
        return 1
    fi
    
    # 检查远程仓库连接
    git remote -v | grep -q origin
    if [ $? -ne 0 ]; then
        log_message "警告: 未配置远程仓库origin"
    fi
    
    return 0
}

# 确保Git配置正确
ensure_git_config() {
    local email=$(git config user.email)
    local name=$(git config user.name)
    
    if [ -z "$email" ]; then
        git config user.email "auto-commit@local.dev"
        log_message "已设置Git邮箱: auto-commit@local.dev"
    fi
    
    if [ -z "$name" ]; then
        git config user.name "Auto Committer"
        log_message "已设置Git用户名: Auto Committer"
    fi
}

# 生成中文提交信息
generate_chinese_commit_with_emoji() {
    # 随机选择一个提交信息
    local commit_index=$((RANDOM % ${#CHINESE_COMMITS[@]}))
    local description_index=$((RANDOM % ${#CHINESE_DESCRIPTIONS[@]}))
    local detail_index=$((RANDOM % ${#CHINESE_DETAILS[@]}))
    echo "${CHINESE_COMMITS[$commit_index]} - ${CHINESE_DESCRIPTIONS[$description_index]}"
}

# 创建或修改跟踪文件
ensure_tracking_file() {
    if [ ! -f "$TS_FILE_PATH" ]; then
        log_message "创建跟踪文件: $TS_FILE_PATH"
        mkdir -p "$(dirname "$TS_FILE_PATH")"
        cat > "$TS_FILE_PATH" << 'EOF'
/**
 * 自动类型追踪文件
 * 此文件用于记录开发活动，不影响功能实现
 */

// 类型定义追踪接口
export interface TrackingData {
  timestamp: number;
  activity: string;
  metadata?: Record<string, unknown>;
}

// 时间戳工具函数
export const getCurrentTimestamp = (): number => Date.now();

// 空操作函数，用于类型检查
export const noop = (): void => {};

EOF
    fi
}

# 生成无害的TS代码修改
generate_harmless_change() {
    # 确保目标文件存在
    ensure_tracking_file
    
    # 获取当前时间戳
    local timestamp=$(date +%s)
    local date_str=$(date '+%Y-%m-%d %H:%M:%S')
    
    # 清空文件，保留头部
    head -n 15 "$TS_FILE_PATH" > "${TS_FILE_PATH}.tmp"
    
    # 生成最多44行的代码
    local max_lines=44
    local header_lines=15
    local remaining_lines=$((max_lines - header_lines))
    
    # 生成代码，控制行数
    for i in {1..15}; do
        case $((RANDOM % 5)) in
            0)
                # 添加导出变量
                local var_names=("trackingId" "timestamp" "debugFlag" "version" "buildId" "commitHash" "userId" "sessionId" "deviceId" "appVersion")
                local var_name=${var_names[$RANDOM % ${#var_names[@]}]}
                echo -e "\nexport const ${var_name}_${timestamp}_${i} = 'autogenerated_${i}';" >> "${TS_FILE_PATH}.tmp"
                ;;
            1)
                # 添加类型定义
                echo -e "\ntype AutoGeneratedType_${timestamp}_${i} = string | number | boolean;" >> "${TS_FILE_PATH}.tmp"
                ;;
            2)
                # 添加接口定义
                echo -e "\ninterface ExtendedTrackingData_${timestamp}_${i} { readonly id: string; timestamp: number; data: Record<string, unknown>; }" >> "${TS_FILE_PATH}.tmp"
                ;;
            3)
                # 添加导出函数
                echo -e "\nexport const getTrackingInfo_${timestamp}_${i} = () => ({ timestamp: ${timestamp}, index: ${i} });" >> "${TS_FILE_PATH}.tmp"
                ;;
            4)
                # 添加注释行
                echo -e "\n// 类型不明确，需要同后端确认类型 ${i} - ${date_str}" >> "${TS_FILE_PATH}.tmp"
                ;;
        esac
    done
    
    # 替换原文件
    mv "${TS_FILE_PATH}.tmp" "$TS_FILE_PATH"
}

# 主执行逻辑
main() {
    # 检查Git仓库
    if ! check_git_status; then
        exit 1
    fi
    
    # 确保Git配置
    ensure_git_config
    
    # 拉取最新更改
    log_message "拉取远程更改..."
    if ! git pull origin "$REMOTE_BRANCH" --quiet; then
        log_message "拉取失败，尝试合并策略"
        git pull --no-rebase origin "$REMOTE_BRANCH" --quiet
    fi
    
    # 生成无害修改
    generate_harmless_change
    
    # 检查是否有实际更改
    if git diff --quiet "$TS_FILE_PATH" 2>/dev/null; then
        # 如果没有更改，添加一个时间戳注释
        echo -e "\n// 更新检查: $(date '+%Y-%m-%d %H:%M:%S')" >> "$TS_FILE_PATH"
        if git diff --quiet "$TS_FILE_PATH"; then
            log_message "没有检测到文件更改，跳过提交"
            exit 0
        fi
    fi
    
    # 添加更改
    git add "$TS_FILE_PATH"
    
    # 生成中文提交信息
    COMMIT_MSG=$(generate_chinese_commit_with_emoji)
    
    # 提交更改
    if git commit -m "$COMMIT_MSG" --quiet; then
        log_message "✅ 提交成功: $COMMIT_MSG"
    else
        log_message "❌ 提交失败"
        exit 1
    fi
    
    # 推送到远程
    log_message "推送更改到远程..."
    if git push origin "$REMOTE_BRANCH" --quiet; then
        local commit_hash=$(git rev-parse --short HEAD)
        log_message "✅ 推送成功! 提交哈希: $commit_hash"
    else
        log_message "❌ 推送失败，尝试强制推送"
        if git push origin "$REMOTE_BRANCH" --quiet --force-with-lease; then
            log_message "✅ 强制推送成功"
        else
            log_message "❌ 推送完全失败"
            exit 1
        fi
    fi
    
    log_message "执行完成"
}

# 捕获脚本退出
trap 'log_message "中断"; exit 1' INT TERM

# 执行主函数
main
